# Generated by Django 6.0 on 2026-04-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin (System Controller)'), ('collector', 'Collector (Waste Collector)'), ('household', 'Household (Resident)')], default='household', max_length=20),
        ),
    ]
