# Generated by Django 6.0 on 2026-07-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartbin',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='smartbin',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
    ]
