# Generated by Django 6.0 on 2026-07-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0002_alter_smartbin_latitude_alter_smartbin_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iotdata',
            options={'ordering': ['-timestamp']},
        ),
    ]
